#
# Makefile
#
# Copyright (C) 2018 shenzhen 100asktech Incorporated - http://www.100ask.org
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y	:= mux.o
endif

obj-y	+= board.o

